services:
  postgres:
    image: postgres:10.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  
  minio:
    image: minio/minio:latest
    ports:
      - '9100:9000'
      - '9101:9001'
    volumes:
      - uploads:/data
    environment:
      MINIO_ROOT_USER: admin@appweave.tech
      MINIO_ROOT_PASSWORD: supersecret
    command: server --console-address ":9001" /data
  
  melisearch:
    image: getmeili/meilisearch:latest
    ports:
      - '7700:7700'
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
volumes:
  node_modules: {}
  uploads: {}